version: "3.8"

services: 
  web: 
    build: .
    working_dir: /app
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - "8000:3000"
    depends_on: 
      - mongo
    networks: 
      - internet

  mongo: 
    image: mongo:6
    volumes: 
      - dbdata:/var/lib/db
    networks: 
      - internet

volumes:
  dbdata:

networks: 
  internet:
